name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "midnight480"
          ICON_FIRST: "#e2e0dc"
          ICON_SECOND: "#cca785"
          BACKGROUND_FIRST: "#887d65"
          BACKGROUND_SECOND: "#fcfcfc"
          LANG: "en"
          CARD_WIDTH: "350"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}